<?php
    print $this->showMessages();
?>

<ul>
<?php
    foreach($this->posts as $post) {
        print '<li>
            <a style="color:darkseagreen" href="' . $this->url('blog', array('action'=>'view', 'id' => $post['id'])) . '">' . $post['title'] . '</a>
            [' . date('d.m.Y H:i', $post['created']). '],
            <a href="' . $this->url('blog', array('action'=>'edit', 'id' => $post['id'])) . '">Изменить</a>,
            <a style="color: red" href="' . $this->url('blog', array('action'=>'delete', 'id' => $post['id'])) . '">Удалить</a>
            </li>';
    }
?>
</ul>